"use client";

import { useState, useEffect, startTransition } from "react";
import Link from "next/link";
import {
  Brain,
  Lock,
  Home,
  FileText,
  Users,
  BarChart3,
  Download,
  LogOut,
  Eye,
  Calendar,
  Clock,
  CheckCircle,
  Zap,
  BookOpen,
} from "lucide-react";

// Types for assessment data
interface AssessmentRecord {
  id: string;
  testType: "brief" | "elaborate";
  completedAt: string;
  answers: Record<string, string>;
  modules: {
    id: string;
    title: string;
    answers: {
      questionId: string;
      question: string;
      answer: string | null;
    }[];
  }[];
}

// Simple password for admin access
const ADMIN_PASSWORD = "phil123";

export default function AdminPage() {
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [assessments, setAssessments] = useState<AssessmentRecord[]>([]);
  const [selectedAssessment, setSelectedAssessment] = useState<AssessmentRecord | null>(null);
  const [activeTab, setActiveTab] = useState<"dashboard" | "assessments" | "navigation">("dashboard");

  // Load assessments from localStorage on mount
  useEffect(() => {
    if (isAuthenticated) {
      // Load all stored assessments
      const storedAssessments: AssessmentRecord[] = [];
      
      // Check for current session results
      const currentResults = sessionStorage.getItem("learnapt-results");
      if (currentResults) {
        try {
          const parsed = JSON.parse(currentResults);
          storedAssessments.push({
            id: `session-${Date.now()}`,
            ...parsed,
          });
        } catch (e) {
          console.error("Failed to parse session results:", e);
        }
      }

      // Load from localStorage history
      const historyStr = localStorage.getItem("learnapt-assessment-history");
      if (historyStr) {
        try {
          const history = JSON.parse(historyStr);
          storedAssessments.push(...history);
        } catch (e) {
          console.error("Failed to parse assessment history:", e);
        }
      }

      startTransition(() => {
        setAssessments(storedAssessments);
      });
    }
  }, [isAuthenticated]);

  const handleLogin = (e: React.FormEvent) => {
    e.preventDefault();
    if (password === ADMIN_PASSWORD) {
      setIsAuthenticated(true);
      setError("");
    } else {
      setError("Invalid password. Please try again.");
    }
  };

  const handleLogout = () => {
    setIsAuthenticated(false);
    setPassword("");
    setSelectedAssessment(null);
  };

  const generateTextContent = (assessment: AssessmentRecord): string => {
    let content = `LEARNAPT ASSESSMENT REPORT\n`;
    content += `${"=".repeat(50)}\n\n`;
    content += `Test Type: ${assessment.testType === "brief" ? "Brief Test" : "Elaborate Test"}\n`;
    content += `Completed: ${new Date(assessment.completedAt).toLocaleString()}\n\n`;
    content += `${"=".repeat(50)}\n`;
    content += `RESPONSES\n`;
    content += `${"=".repeat(50)}\n\n`;

    assessment.modules.forEach((module) => {
      content += `\n--- ${module.title} ---\n\n`;
      module.answers.forEach((answer, idx) => {
        content += `Q${idx + 1}: ${answer.question}\n`;
        content += `A: ${answer.answer || "Not answered"}\n\n`;
      });
    });

    content += `\n${"=".repeat(50)}\n`;
    content += `Generated by Learnapt - ${new Date().toLocaleString()}\n`;

    return content;
  };

  const downloadAsText = (assessment: AssessmentRecord) => {
    const content = generateTextContent(assessment);
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `learnapt-assessment-${assessment.testType}-${new Date(assessment.completedAt).toISOString().split("T")[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const downloadAsHTML = (assessment: AssessmentRecord) => {
    let html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Learnapt Assessment Report</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
    h1 { color: #3b82f6; }
    h2 { color: #6366f1; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px; }
    .module { margin: 20px 0; padding: 15px; background: #f8fafc; border-radius: 8px; }
    .question { margin: 10px 0; }
    .question-text { font-weight: bold; }
    .answer { color: #059669; margin-left: 20px; }
    .meta { color: #64748b; font-size: 14px; }
    .header { background: linear-gradient(135deg, #3b82f6, #8b5cf6); color: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🧠 Learnapt Assessment Report</h1>
    <p class="meta">Test Type: ${assessment.testType === "brief" ? "Brief Test" : "Elaborate Test"}</p>
    <p class="meta">Completed: ${new Date(assessment.completedAt).toLocaleString()}</p>
  </div>
  <h2>Responses</h2>`;

    assessment.modules.forEach((module) => {
      html += `<div class="module"><h3>${module.title}</h3>`;
      module.answers.forEach((answer, idx) => {
        html += `<div class="question">
          <p class="question-text">Q${idx + 1}: ${answer.question}</p>
          <p class="answer">Answer: ${answer.answer || "Not answered"}</p>
        </div>`;
      });
      html += `</div>`;
    });

    html += `<p class="meta" style="margin-top: 30px; text-align: center;">Generated by Learnapt - ${new Date().toLocaleString()}</p>
</body>
</html>`;

    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `learnapt-assessment-${assessment.testType}-${new Date(assessment.completedAt).toISOString().split("T")[0]}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Login Screen
  if (!isAuthenticated) {
    return (
      <div className="min-h-screen bg-gradient-to-b from-slate-50 to-slate-100 dark:from-slate-900 dark:to-slate-800 flex items-center justify-center p-4">
        <div className="w-full max-w-md">
          <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-xl p-8">
            <div className="text-center mb-8">
              <div className="inline-flex items-center justify-center w-16 h-16 bg-blue-100 dark:bg-blue-900/50 rounded-full mb-4">
                <Lock className="h-8 w-8 text-blue-600" />
              </div>
              <h1 className="text-2xl font-bold text-slate-900 dark:text-white">Admin Login</h1>
              <p className="text-slate-600 dark:text-slate-400 mt-2">
                Enter password to access the admin panel
              </p>
            </div>

            <form onSubmit={handleLogin} className="space-y-4">
              <div>
                <label htmlFor="password" className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
                  Password
                </label>
                <input
                  type="password"
                  id="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  className="w-full px-4 py-3 border border-slate-300 dark:border-slate-600 rounded-lg bg-white dark:bg-slate-700 text-slate-900 dark:text-white focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  placeholder="Enter admin password"
                  autoFocus
                />
              </div>

              {error && (
                <p className="text-red-500 text-sm">{error}</p>
              )}

              <button
                type="submit"
                className="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 px-4 rounded-lg transition-colors"
              >
                Login
              </button>
            </form>

            <div className="mt-6 text-center">
              <Link href="/" className="text-blue-600 hover:text-blue-700 text-sm inline-flex items-center gap-1">
                <Home className="h-4 w-4" />
                Back to Home
              </Link>
            </div>
          </div>
        </div>
      </div>
    );
  }

  // Admin Dashboard
  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-50 to-slate-100 dark:from-slate-900 dark:to-slate-800">
      {/* Header */}
      <header className="border-b border-slate-200 dark:border-slate-700 bg-white/80 dark:bg-slate-900/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <div className="flex items-center gap-2">
              <Brain className="h-8 w-8 text-blue-600" />
              <span className="text-xl font-bold text-slate-900 dark:text-white">Learnapt Admin</span>
            </div>
            <button
              onClick={handleLogout}
              className="flex items-center gap-2 text-slate-600 hover:text-red-600 dark:text-slate-400 dark:hover:text-red-400 transition-colors"
            >
              <LogOut className="h-5 w-5" />
              Logout
            </button>
          </div>
        </div>
      </header>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Tab Navigation */}
        <div className="flex gap-2 mb-8 border-b border-slate-200 dark:border-slate-700">
          <button
            onClick={() => setActiveTab("dashboard")}
            className={`px-4 py-2 font-medium transition-colors border-b-2 -mb-px ${
              activeTab === "dashboard"
                ? "border-blue-600 text-blue-600"
                : "border-transparent text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white"
            }`}
          >
            <BarChart3 className="h-4 w-4 inline-block mr-2" />
            Dashboard
          </button>
          <button
            onClick={() => setActiveTab("assessments")}
            className={`px-4 py-2 font-medium transition-colors border-b-2 -mb-px ${
              activeTab === "assessments"
                ? "border-blue-600 text-blue-600"
                : "border-transparent text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white"
            }`}
          >
            <FileText className="h-4 w-4 inline-block mr-2" />
            Assessments
          </button>
          <button
            onClick={() => setActiveTab("navigation")}
            className={`px-4 py-2 font-medium transition-colors border-b-2 -mb-px ${
              activeTab === "navigation"
                ? "border-blue-600 text-blue-600"
                : "border-transparent text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white"
            }`}
          >
            <Eye className="h-4 w-4 inline-block mr-2" />
            Site Navigation
          </button>
        </div>

        {/* Dashboard Tab */}
        {activeTab === "dashboard" && (
          <div className="space-y-6">
            {/* Stats Cards */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
              <div className="bg-white dark:bg-slate-800 rounded-xl p-6 shadow-lg">
                <div className="flex items-center gap-4">
                  <div className="p-3 bg-blue-100 dark:bg-blue-900/50 rounded-lg">
                    <Users className="h-6 w-6 text-blue-600" />
                  </div>
                  <div>
                    <p className="text-sm text-slate-600 dark:text-slate-400">Total Assessments</p>
                    <p className="text-2xl font-bold text-slate-900 dark:text-white">{assessments.length}</p>
                  </div>
                </div>
              </div>

              <div className="bg-white dark:bg-slate-800 rounded-xl p-6 shadow-lg">
                <div className="flex items-center gap-4">
                  <div className="p-3 bg-purple-100 dark:bg-purple-900/50 rounded-lg">
                    <Zap className="h-6 w-6 text-purple-600" />
                  </div>
                  <div>
                    <p className="text-sm text-slate-600 dark:text-slate-400">Brief Tests</p>
                    <p className="text-2xl font-bold text-slate-900 dark:text-white">
                      {assessments.filter((a) => a.testType === "brief").length}
                    </p>
                  </div>
                </div>
              </div>

              <div className="bg-white dark:bg-slate-800 rounded-xl p-6 shadow-lg">
                <div className="flex items-center gap-4">
                  <div className="p-3 bg-green-100 dark:bg-green-900/50 rounded-lg">
                    <BookOpen className="h-6 w-6 text-green-600" />
                  </div>
                  <div>
                    <p className="text-sm text-slate-600 dark:text-slate-400">Elaborate Tests</p>
                    <p className="text-2xl font-bold text-slate-900 dark:text-white">
                      {assessments.filter((a) => a.testType === "elaborate").length}
                    </p>
                  </div>
                </div>
              </div>

              <div className="bg-white dark:bg-slate-800 rounded-xl p-6 shadow-lg">
                <div className="flex items-center gap-4">
                  <div className="p-3 bg-amber-100 dark:bg-amber-900/50 rounded-lg">
                    <CheckCircle className="h-6 w-6 text-amber-600" />
                  </div>
                  <div>
                    <p className="text-sm text-slate-600 dark:text-slate-400">Completion Rate</p>
                    <p className="text-2xl font-bold text-slate-900 dark:text-white">100%</p>
                  </div>
                </div>
              </div>
            </div>

            {/* Recent Activity */}
            <div className="bg-white dark:bg-slate-800 rounded-xl p-6 shadow-lg">
              <h2 className="text-lg font-bold text-slate-900 dark:text-white mb-4">Recent Activity</h2>
              {assessments.length === 0 ? (
                <p className="text-slate-600 dark:text-slate-400 text-center py-8">
                  No assessments recorded yet. Assessments will appear here when users complete tests.
                </p>
              ) : (
                <div className="space-y-3">
                  {assessments.slice(0, 5).map((assessment) => (
                    <div
                      key={assessment.id}
                      className="flex items-center justify-between p-3 bg-slate-50 dark:bg-slate-700/50 rounded-lg"
                    >
                      <div className="flex items-center gap-3">
                        {assessment.testType === "brief" ? (
                          <Zap className="h-5 w-5 text-blue-600" />
                        ) : (
                          <BookOpen className="h-5 w-5 text-purple-600" />
                        )}
                        <div>
                          <p className="font-medium text-slate-900 dark:text-white">
                            {assessment.testType === "brief" ? "Brief Test" : "Elaborate Test"}
                          </p>
                          <p className="text-sm text-slate-600 dark:text-slate-400">
                            <Calendar className="h-3 w-3 inline mr-1" />
                            {new Date(assessment.completedAt).toLocaleDateString()}
                            <Clock className="h-3 w-3 inline ml-3 mr-1" />
                            {new Date(assessment.completedAt).toLocaleTimeString()}
                          </p>
                        </div>
                      </div>
                      <button
                        onClick={() => {
                          setSelectedAssessment(assessment);
                          setActiveTab("assessments");
                        }}
                        className="text-blue-600 hover:text-blue-700 text-sm font-medium"
                      >
                        View
                      </button>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        )}

        {/* Assessments Tab */}
        {activeTab === "assessments" && (
          <div className="space-y-6">
            {selectedAssessment ? (
              <div className="bg-white dark:bg-slate-800 rounded-xl p-6 shadow-lg">
                <div className="flex items-center justify-between mb-6">
                  <div>
                    <h2 className="text-xl font-bold text-slate-900 dark:text-white">
                      {selectedAssessment.testType === "brief" ? "Brief Test" : "Elaborate Test"} Results
                    </h2>
                    <p className="text-slate-600 dark:text-slate-400">
                      Completed: {new Date(selectedAssessment.completedAt).toLocaleString()}
                    </p>
                  </div>
                  <div className="flex gap-2">
                    <button
                      onClick={() => downloadAsText(selectedAssessment)}
                      className="flex items-center gap-2 bg-slate-200 hover:bg-slate-300 dark:bg-slate-700 dark:hover:bg-slate-600 text-slate-900 dark:text-white px-4 py-2 rounded-lg transition-colors"
                    >
                      <Download className="h-4 w-4" />
                      Download TXT
                    </button>
                    <button
                      onClick={() => downloadAsHTML(selectedAssessment)}
                      className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg transition-colors"
                    >
                      <Download className="h-4 w-4" />
                      Download HTML
                    </button>
                    <button
                      onClick={() => setSelectedAssessment(null)}
                      className="text-slate-600 hover:text-slate-900 dark:text-slate-400 dark:hover:text-white px-4 py-2"
                    >
                      Back
                    </button>
                  </div>
                </div>

                {/* Assessment Details */}
                <div className="space-y-6">
                  {selectedAssessment.modules.map((module) => (
                    <div key={module.id} className="border border-slate-200 dark:border-slate-700 rounded-lg p-4">
                      <h3 className="font-semibold text-slate-900 dark:text-white mb-4">{module.title}</h3>
                      <div className="space-y-3">
                        {module.answers.map((answer, idx) => (
                          <div key={answer.questionId} className="bg-slate-50 dark:bg-slate-700/50 rounded-lg p-3">
                            <p className="text-sm font-medium text-slate-700 dark:text-slate-300">
                              Q{idx + 1}: {answer.question}
                            </p>
                            <p className="text-sm text-green-600 dark:text-green-400 mt-1">
                              Answer: {answer.answer || "Not answered"}
                            </p>
                          </div>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ) : (
              <div className="bg-white dark:bg-slate-800 rounded-xl p-6 shadow-lg">
                <h2 className="text-lg font-bold text-slate-900 dark:text-white mb-4">All Assessments</h2>
                {assessments.length === 0 ? (
                  <p className="text-slate-600 dark:text-slate-400 text-center py-8">
                    No assessments recorded yet.
                  </p>
                ) : (
                  <div className="space-y-3">
                    {assessments.map((assessment) => (
                      <div
                        key={assessment.id}
                        className="flex items-center justify-between p-4 border border-slate-200 dark:border-slate-700 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-700/50 transition-colors"
                      >
                        <div className="flex items-center gap-4">
                          {assessment.testType === "brief" ? (
                            <div className="p-2 bg-blue-100 dark:bg-blue-900/50 rounded-lg">
                              <Zap className="h-5 w-5 text-blue-600" />
                            </div>
                          ) : (
                            <div className="p-2 bg-purple-100 dark:bg-purple-900/50 rounded-lg">
                              <BookOpen className="h-5 w-5 text-purple-600" />
                            </div>
                          )}
                          <div>
                            <p className="font-medium text-slate-900 dark:text-white">
                              {assessment.testType === "brief" ? "Brief Test" : "Elaborate Test"}
                            </p>
                            <p className="text-sm text-slate-600 dark:text-slate-400">
                              {new Date(assessment.completedAt).toLocaleString()}
                            </p>
                          </div>
                        </div>
                        <div className="flex gap-2">
                          <button
                            onClick={() => setSelectedAssessment(assessment)}
                            className="flex items-center gap-1 text-blue-600 hover:text-blue-700 text-sm font-medium"
                          >
                            <Eye className="h-4 w-4" />
                            View
                          </button>
                          <button
                            onClick={() => downloadAsText(assessment)}
                            className="flex items-center gap-1 text-slate-600 hover:text-slate-900 dark:text-slate-400 dark:hover:text-white text-sm"
                          >
                            <Download className="h-4 w-4" />
                            TXT
                          </button>
                          <button
                            onClick={() => downloadAsHTML(assessment)}
                            className="flex items-center gap-1 text-slate-600 hover:text-slate-900 dark:text-slate-400 dark:hover:text-white text-sm"
                          >
                            <Download className="h-4 w-4" />
                            HTML
                          </button>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}
          </div>
        )}

        {/* Navigation Tab */}
        {activeTab === "navigation" && (
          <div className="space-y-6">
            <div className="bg-white dark:bg-slate-800 rounded-xl p-6 shadow-lg">
              <h2 className="text-lg font-bold text-slate-900 dark:text-white mb-4">Site Navigation</h2>
              <p className="text-slate-600 dark:text-slate-400 mb-6">
                Quick access to all sections of the Learnapt application.
              </p>

              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                <Link
                  href="/"
                  className="flex items-center gap-4 p-4 border border-slate-200 dark:border-slate-700 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-700/50 transition-colors"
                >
                  <div className="p-3 bg-slate-100 dark:bg-slate-700 rounded-lg">
                    <Home className="h-6 w-6 text-slate-600 dark:text-slate-400" />
                  </div>
                  <div>
                    <p className="font-medium text-slate-900 dark:text-white">Home</p>
                    <p className="text-sm text-slate-600 dark:text-slate-400">Landing page</p>
                  </div>
                </Link>

                <Link
                  href="/brief-test"
                  className="flex items-center gap-4 p-4 border border-slate-200 dark:border-slate-700 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-700/50 transition-colors"
                >
                  <div className="p-3 bg-blue-100 dark:bg-blue-900/50 rounded-lg">
                    <Zap className="h-6 w-6 text-blue-600" />
                  </div>
                  <div>
                    <p className="font-medium text-slate-900 dark:text-white">Brief Test</p>
                    <p className="text-sm text-slate-600 dark:text-slate-400">9 questions, ~5 min</p>
                  </div>
                </Link>

                <Link
                  href="/elaborate-test"
                  className="flex items-center gap-4 p-4 border border-slate-200 dark:border-slate-700 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-700/50 transition-colors"
                >
                  <div className="p-3 bg-purple-100 dark:bg-purple-900/50 rounded-lg">
                    <BookOpen className="h-6 w-6 text-purple-600" />
                  </div>
                  <div>
                    <p className="font-medium text-slate-900 dark:text-white">Elaborate Test</p>
                    <p className="text-sm text-slate-600 dark:text-slate-400">25 questions, ~15-20 min</p>
                  </div>
                </Link>

                <Link
                  href="/results"
                  className="flex items-center gap-4 p-4 border border-slate-200 dark:border-slate-700 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-700/50 transition-colors"
                >
                  <div className="p-3 bg-green-100 dark:bg-green-900/50 rounded-lg">
                    <BarChart3 className="h-6 w-6 text-green-600" />
                  </div>
                  <div>
                    <p className="font-medium text-slate-900 dark:text-white">Results</p>
                    <p className="text-sm text-slate-600 dark:text-slate-400">View assessment results</p>
                  </div>
                </Link>

                <Link
                  href="/admin"
                  className="flex items-center gap-4 p-4 border border-blue-200 dark:border-blue-700 bg-blue-50 dark:bg-blue-900/20 rounded-lg"
                >
                  <div className="p-3 bg-blue-100 dark:bg-blue-900/50 rounded-lg">
                    <Lock className="h-6 w-6 text-blue-600" />
                  </div>
                  <div>
                    <p className="font-medium text-slate-900 dark:text-white">Admin Panel</p>
                    <p className="text-sm text-slate-600 dark:text-slate-400">Current page</p>
                  </div>
                </Link>
              </div>
            </div>

            {/* Open in New Tab Section */}
            <div className="bg-white dark:bg-slate-800 rounded-xl p-6 shadow-lg">
              <h2 className="text-lg font-bold text-slate-900 dark:text-white mb-4">Open in New Tab</h2>
              <div className="flex flex-wrap gap-3">
                <a
                  href="/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 bg-slate-200 hover:bg-slate-300 dark:bg-slate-700 dark:hover:bg-slate-600 text-slate-900 dark:text-white px-4 py-2 rounded-lg transition-colors"
                >
                  <Home className="h-4 w-4" />
                  Home
                </a>
                <a
                  href="/brief-test"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg transition-colors"
                >
                  <Zap className="h-4 w-4" />
                  Brief Test
                </a>
                <a
                  href="/elaborate-test"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 bg-purple-600 hover:bg-purple-700 text-white px-4 py-2 rounded-lg transition-colors"
                >
                  <BookOpen className="h-4 w-4" />
                  Elaborate Test
                </a>
                <a
                  href="/results"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg transition-colors"
                >
                  <BarChart3 className="h-4 w-4" />
                  Results
                </a>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
